import type { Metadata } from "next";
import { cookies } from "next/headers";
import { SupportedLanguages, type Lang } from "@/lib/i18n";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const c = await cookies();
  const raw = c.get("lang")?.value as Lang | undefined;
  const lang = (SupportedLanguages as readonly string[]).includes(String(raw)) ? raw! : "zh-CN";
  return (
    <html lang={lang}>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased sky-bg min-h-screen`}
      >
        {/* 顶部导航与访问统计 */}
        <div id="nav">
        </div>
        {children}
      </body>
    </html>
  );
}
